# Generated by Django 6.0.5 on 2026-05-10 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('reaction', models.CharField(choices=[('(◎_◎;)', '(◎_◎;)'), ('ヽ(•‿•)ノ', 'ヽ(•‿•)ノ'), ('ψ(｀∇´)ψ', 'ψ(｀∇´)ψ'), ('(ノಠ益ಠ)ノ彡┻━┻', '(ノಠ益ಠ)ノ彡┻━┻'), ('(╯°□°）╯︵ ┻━┻', '(╯°□°）╯︵ ┻━┻'), ('┐(´д`)┌', '┐(´д`)┌'), ('(づ｡◕‿‿◕｡)づ', '(づ｡◕‿‿◕｡)づ'), ('(⌐■_■)', '(⌐■_■)'), ('ᕦ(ò_óˇ)ᕤ', 'ᕦ(ò_óˇ)ᕤ'), ('(눈_눈)', '(눈_눈)'), ('(-_-)', '(-_-)'), ('༼ つ ◕_◕ ༽つ', '༼ つ ◕_◕ ༽つ'), ('', 'No Reaction')], default='', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_message', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
