# Generated by Django 6.0.5 on 2026-05-16 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('reaction', models.CharField(choices=[('😵', '😵 Confused'), ('😄', '😄 Happy'), ('😈', '😈 Evil'), ('😡', '😡 Rage'), ('🤬', '🤬 Table Flip'), ('🤷', '🤷 Shrugging'), ('🥰', '🥰 Cute'), ('😎', '😎 Sigma'), ('💪', '💪 Fight'), ('🤨', '🤨 Sus'), ('😮\u200d💨', '😮\u200d💨 Exhausted'), ('✨', '✨ Extra'), ('', 'No Reaction')], default='', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_message', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.room')),
            ],
        ),
    ]
