# Generated by Django 6.0.5 on 2026-05-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reaction',
            field=models.CharField(choices=[('(◎_◎;)', '(◎_◎;)'), ('ヽ(•‿•)ノ', 'ヽ(•‿•)ノ'), ('ψ(｀∇´)ψ', 'ψ(｀∇´)ψ'), ('(ノಠ益ಠ)ノ彡┻━┻', '(ノಠ益ಠ)ノ彡┻━┻'), ('(╯°□°）╯︵ ┻━┻', '(╯°□°）╯︵ ┻━┻'), ('┐(´д`)┌', '┐(´д`)┌'), ('(づ｡◕‿‿◕｡)づ', '(づ｡◕‿‿◕｡)づ'), ('(⌐■_■)', '(⌐■_■)'), ('ᕦ(ò_óˇ)ᕤ', 'ᕦ(ò_óˇ)ᕤ'), ('(눈_눈)', '(눈_눈)'), ('(-_-)', '(-_-)'), ('༼ つ ◕_◕ ༽つ', '༼ つ ◕_◕ ༽つ'), ('', '')], default='', max_length=50),
        ),
    ]
